### PR TITLE
Add support for certificates without AllowPlaintextExport

### LINKED ISSUE #10: Unable to import certificates generated with New-SelfSignedCertificate
I'm experiencing problems when attempting to use TPMImport with certificates generated with [New-SelfSignedCertificate](https://learn.microsoft.com/en-us/powershell/module/pki/new-selfsignedcertificate). This problem seem to have been there since at least v1.1.

It seems like the root cause is that the `AllowPlaintextExport` flag is missing for the loaded PFX file:
image

StackOverflow link: https://stackoverflow.com/questions/57269726/x509certificate2-import-with-ncrypt-allow-plaintext-export-flag

## Steps to reproduce
* Create `GenerateCertificates.ps1` with the following content:
```
# PFX password (haven't figured out how to avoid it)
$pwd = ConvertTo-SecureString -String "1234" -AsPlainText -Force
# Create certificate in CurrentUser\Private store (need to be cleaned up manually)
$cert = New-SelfSignedCertificate -DnsName "my.own.domain" -CertStoreLocation "cert:\CurrentUser\My" -KeyAlgorithm RSA -KeyLength 2048 -KeyExportPolicy Exportable
Export-PfxCertificate -Cert $cert -Password $pwd -FilePath "myOwnDomain.pfx"
```
* Run `powershell .\GenerateCertificates.ps1` to generate "myOwnDomain.pfx"
* Run `TPMImport.exe -user myOwnDomain.pfx 1234` and observe the following error: `Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException: 'The requested operation is not supported.'`

Call stack:
```
System.Security.Cryptography.Cng.dll!System.Security.Cryptography.CngKey.Export(System.Security.Cryptography.CngKeyBlobFormat format) Line 24
System.Security.Cryptography.Cng.dll!System.Security.Cryptography.RSACng.ExportKeyBlob(bool includePrivateParameters) Line 35
System.Security.Cryptography.Cng.dll!System.Security.Cryptography.RSACng.ExportParameters(bool includePrivateParameters) Line 292
System.Security.Cryptography.Algorithms.dll!System.Security.Cryptography.RSA.ToXmlString(bool includePrivateParameters) Line 110
TPMImport.dll!TPMImport.Program.Main(string[] args) Line 108
```

The failing call seem to be [`Interop.NCrypt.NCryptExportKey(_keyHandle, IntPtr.Zero, "RSAFULLPRIVATEBLOB", IntPtr.Zero, null, 0, out numBytesNeeded, 0)`](https://github.com/dotnet/runtime/blob/v6.0.0/src/libraries/System.Security.Cryptography.Cng/src/System/Security/Cryptography/CngKey.Export.cs#L27) returning NTE_NOT_SUPPORTED.

### PR DESCRIPTION
**Pull request by forderud**
Fixes #10.

Certificates that are generated by [New-SelfSignedCertificate](https://learn.microsoft.com/en-us/powershell/module/pki/new-selfsignedcertificate) seem to lack the `AllowPlaintextExport` flag, even when being generated with "-KeyExportPolicy Exportable". Instead, only the AllowExport flag is set.

This PR works around that problem by exporting & reimporting the private key. This will for some reason set the AllowPlaintextExport flag. Based on suggestion by sindremb on https://learn.microsoft.com/en-us/answers/questions/280592/ncrypt-allow-plaintext-export-flag-removed-during.html

### CODE REVIEW

**Comment by bb-froggy** [comment]
Thanks for all the improvements to this project! Sorry that I didn't look at them earlier ... I got a serious cold (no Corona) and work piled up after I came back.

**Comment by forderud** [comment]
No problem. Hope you're feeling better now. It's definitely worth the wait for me! I really appreciate this project and your reviews to quality-assure my changes. TPM usage on Windows feels a bit like a "black art" with many unforeseen problems, and I don't have anyone else to discuss these issues with.

**Comment by bb-froggy** [comment]
I am unsure as to whether we are really "allowed" to import the key if it hasn't got the AllowPlaintextExport. But since your patch works, who are we to prevent people from doing it? Probably this just adds to your black art comment ... it looks strange, but it does what you want if you adhere to the rites ;-)

**Comment by forderud** [comment]
> I am unsure as to whether we are really "allowed" to import the key if it hasn't got the AllowPlaintextExport. But since your patch works, who are we to prevent people from doing it? Probably this just adds to your black art comment ... it looks strange, but it does what you want if you adhere to the rites ;-)

The certificate still has the `AllowExport` flag set, so key export (in encrypted form) is supposed to work. The only change is that we tweak the RSA key to also allow unencrypted export. This is conceptually similar to allowing unencrypted PFX storage.

**Comment by forderud** [comment]
@bb-froggy Sorry for continuing to bother you with this project, but would it be possible to request a new binary release of this project now that this PR is merged?

The reason for asking is that it would be preferable to use official TPMImport binaries instead of building and distributing unofficial binaries.

**Comment by bb-froggy** [comment]
@forderud : There is now a new Release: https://github.com/glueckkanja-pki/TPMImport/releases/tag/20221028-1210-core

**Comment by forderud** [comment]
Perfect! Thanks a lot :-)

**Pull request merged**
